name: Run cdk8s Demo Script

on:
  workflow_dispatch:  # Triggered manually from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip git helm kubectl
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt install -y nodejs
          npm install -g cdk8s-cli
          go install github.com/aws/jsii-release/go/cmd/jsii@latest || true

      - name: Run cdk8s demo script
        run: |
          set +e  # Continue on error
          git clone https://github.com/vfarcic/cdk8s-demo
          cd cdk8s-demo || exit 0

          helm repo add crossplane-stable https://charts.crossplane.io/stable
          helm repo update

          helm upgrade --install crossplane crossplane-stable/crossplane \
            --namespace crossplane-system --create-namespace --wait

          kubectl apply --filename crossplane/provider-aws.yaml || true
          kubectl apply --filename crossplane/provider-sql.yaml || true

          cdk8s init go-app || true
          cdk8s synth || true

          cdk8s import github:crossplane/crossplane@1.9.1 --language go || true

          kubectl get crd --output json | cdk8s import /dev/stdin --language go || true

          chmod +x get-crds.sh || true
          ./get-crds.sh || true

          cdk8s import crds/crossplane.yaml --language go || true
